/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ConsentRegistry__factory } from "./ConsentRegistry__factory";
export { Counter__factory } from "./Counter__factory";
export { DoctorRegistry__factory } from "./DoctorRegistry__factory";
export { EscrowPayments__factory } from "./EscrowPayments__factory";
export { InstaDocHub__factory } from "./InstaDocHub__factory";
export { PatientRecords__factory } from "./PatientRecords__factory";
