/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface EscrowPaymentsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "appointments"
      | "bookAppointment"
      | "cancelByDoctor"
      | "cancelByPatient"
      | "completeAppointment"
      | "confirmAppointment"
      | "disputeAppointment"
      | "getPatientAppointments"
      | "nextAppointmentId"
      | "resolveDispute"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AppointmentBooked"
      | "AppointmentCancelledByDoctor"
      | "AppointmentCancelledByPatient"
      | "AppointmentCompleted"
      | "AppointmentConfirmed"
      | "AppointmentDisputed"
      | "FundsReleased"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "appointments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bookAppointment",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelByDoctor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelByPatient",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeAppointment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmAppointment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeAppointment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPatientAppointments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextAppointmentId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "appointments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bookAppointment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelByDoctor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelByPatient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeAppointment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmAppointment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeAppointment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPatientAppointments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextAppointmentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
}

export namespace AppointmentBookedEvent {
  export type InputTuple = [
    appointmentId: BigNumberish,
    patient: AddressLike,
    doctor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    appointmentId: bigint,
    patient: string,
    doctor: string,
    amount: bigint
  ];
  export interface OutputObject {
    appointmentId: bigint;
    patient: string;
    doctor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AppointmentCancelledByDoctorEvent {
  export type InputTuple = [appointmentId: BigNumberish];
  export type OutputTuple = [appointmentId: bigint];
  export interface OutputObject {
    appointmentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AppointmentCancelledByPatientEvent {
  export type InputTuple = [appointmentId: BigNumberish];
  export type OutputTuple = [appointmentId: bigint];
  export interface OutputObject {
    appointmentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AppointmentCompletedEvent {
  export type InputTuple = [appointmentId: BigNumberish];
  export type OutputTuple = [appointmentId: bigint];
  export interface OutputObject {
    appointmentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AppointmentConfirmedEvent {
  export type InputTuple = [appointmentId: BigNumberish];
  export type OutputTuple = [appointmentId: bigint];
  export interface OutputObject {
    appointmentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AppointmentDisputedEvent {
  export type InputTuple = [appointmentId: BigNumberish];
  export type OutputTuple = [appointmentId: bigint];
  export interface OutputObject {
    appointmentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedEvent {
  export type InputTuple = [
    appointmentId: BigNumberish,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [appointmentId: bigint, to: string, amount: bigint];
  export interface OutputObject {
    appointmentId: bigint;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowPayments extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowPayments;
  waitForDeployment(): Promise<this>;

  interface: EscrowPaymentsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  appointments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        patient: string;
        doctor: string;
        amount: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  bookAppointment: TypedContractMethod<
    [doctor: AddressLike],
    [bigint],
    "payable"
  >;

  cancelByDoctor: TypedContractMethod<
    [appointmentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelByPatient: TypedContractMethod<
    [appointmentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  completeAppointment: TypedContractMethod<
    [appointmentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  confirmAppointment: TypedContractMethod<
    [appointmentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  disputeAppointment: TypedContractMethod<
    [appointmentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getPatientAppointments: TypedContractMethod<
    [patient: AddressLike],
    [bigint[]],
    "view"
  >;

  nextAppointmentId: TypedContractMethod<[], [bigint], "view">;

  resolveDispute: TypedContractMethod<
    [appointmentId: BigNumberish, winner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "appointments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        patient: string;
        doctor: string;
        amount: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "bookAppointment"
  ): TypedContractMethod<[doctor: AddressLike], [bigint], "payable">;
  getFunction(
    nameOrSignature: "cancelByDoctor"
  ): TypedContractMethod<[appointmentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelByPatient"
  ): TypedContractMethod<[appointmentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeAppointment"
  ): TypedContractMethod<[appointmentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmAppointment"
  ): TypedContractMethod<[appointmentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "disputeAppointment"
  ): TypedContractMethod<[appointmentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPatientAppointments"
  ): TypedContractMethod<[patient: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "nextAppointmentId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [appointmentId: BigNumberish, winner: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AppointmentBooked"
  ): TypedContractEvent<
    AppointmentBookedEvent.InputTuple,
    AppointmentBookedEvent.OutputTuple,
    AppointmentBookedEvent.OutputObject
  >;
  getEvent(
    key: "AppointmentCancelledByDoctor"
  ): TypedContractEvent<
    AppointmentCancelledByDoctorEvent.InputTuple,
    AppointmentCancelledByDoctorEvent.OutputTuple,
    AppointmentCancelledByDoctorEvent.OutputObject
  >;
  getEvent(
    key: "AppointmentCancelledByPatient"
  ): TypedContractEvent<
    AppointmentCancelledByPatientEvent.InputTuple,
    AppointmentCancelledByPatientEvent.OutputTuple,
    AppointmentCancelledByPatientEvent.OutputObject
  >;
  getEvent(
    key: "AppointmentCompleted"
  ): TypedContractEvent<
    AppointmentCompletedEvent.InputTuple,
    AppointmentCompletedEvent.OutputTuple,
    AppointmentCompletedEvent.OutputObject
  >;
  getEvent(
    key: "AppointmentConfirmed"
  ): TypedContractEvent<
    AppointmentConfirmedEvent.InputTuple,
    AppointmentConfirmedEvent.OutputTuple,
    AppointmentConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "AppointmentDisputed"
  ): TypedContractEvent<
    AppointmentDisputedEvent.InputTuple,
    AppointmentDisputedEvent.OutputTuple,
    AppointmentDisputedEvent.OutputObject
  >;
  getEvent(
    key: "FundsReleased"
  ): TypedContractEvent<
    FundsReleasedEvent.InputTuple,
    FundsReleasedEvent.OutputTuple,
    FundsReleasedEvent.OutputObject
  >;

  filters: {
    "AppointmentBooked(uint256,address,address,uint256)": TypedContractEvent<
      AppointmentBookedEvent.InputTuple,
      AppointmentBookedEvent.OutputTuple,
      AppointmentBookedEvent.OutputObject
    >;
    AppointmentBooked: TypedContractEvent<
      AppointmentBookedEvent.InputTuple,
      AppointmentBookedEvent.OutputTuple,
      AppointmentBookedEvent.OutputObject
    >;

    "AppointmentCancelledByDoctor(uint256)": TypedContractEvent<
      AppointmentCancelledByDoctorEvent.InputTuple,
      AppointmentCancelledByDoctorEvent.OutputTuple,
      AppointmentCancelledByDoctorEvent.OutputObject
    >;
    AppointmentCancelledByDoctor: TypedContractEvent<
      AppointmentCancelledByDoctorEvent.InputTuple,
      AppointmentCancelledByDoctorEvent.OutputTuple,
      AppointmentCancelledByDoctorEvent.OutputObject
    >;

    "AppointmentCancelledByPatient(uint256)": TypedContractEvent<
      AppointmentCancelledByPatientEvent.InputTuple,
      AppointmentCancelledByPatientEvent.OutputTuple,
      AppointmentCancelledByPatientEvent.OutputObject
    >;
    AppointmentCancelledByPatient: TypedContractEvent<
      AppointmentCancelledByPatientEvent.InputTuple,
      AppointmentCancelledByPatientEvent.OutputTuple,
      AppointmentCancelledByPatientEvent.OutputObject
    >;

    "AppointmentCompleted(uint256)": TypedContractEvent<
      AppointmentCompletedEvent.InputTuple,
      AppointmentCompletedEvent.OutputTuple,
      AppointmentCompletedEvent.OutputObject
    >;
    AppointmentCompleted: TypedContractEvent<
      AppointmentCompletedEvent.InputTuple,
      AppointmentCompletedEvent.OutputTuple,
      AppointmentCompletedEvent.OutputObject
    >;

    "AppointmentConfirmed(uint256)": TypedContractEvent<
      AppointmentConfirmedEvent.InputTuple,
      AppointmentConfirmedEvent.OutputTuple,
      AppointmentConfirmedEvent.OutputObject
    >;
    AppointmentConfirmed: TypedContractEvent<
      AppointmentConfirmedEvent.InputTuple,
      AppointmentConfirmedEvent.OutputTuple,
      AppointmentConfirmedEvent.OutputObject
    >;

    "AppointmentDisputed(uint256)": TypedContractEvent<
      AppointmentDisputedEvent.InputTuple,
      AppointmentDisputedEvent.OutputTuple,
      AppointmentDisputedEvent.OutputObject
    >;
    AppointmentDisputed: TypedContractEvent<
      AppointmentDisputedEvent.InputTuple,
      AppointmentDisputedEvent.OutputTuple,
      AppointmentDisputedEvent.OutputObject
    >;

    "FundsReleased(uint256,address,uint256)": TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
    FundsReleased: TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
  };
}
