/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ConsentRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ConsentRegistry__factory>;
    getContractFactory(
      name: "Counter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Counter__factory>;
    getContractFactory(
      name: "DoctorRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DoctorRegistry__factory>;
    getContractFactory(
      name: "EscrowPayments",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EscrowPayments__factory>;
    getContractFactory(
      name: "InstaDocHub",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InstaDocHub__factory>;
    getContractFactory(
      name: "PatientRecords",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PatientRecords__factory>;

    getContractAt(
      name: "ConsentRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ConsentRegistry>;
    getContractAt(
      name: "Counter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Counter>;
    getContractAt(
      name: "DoctorRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DoctorRegistry>;
    getContractAt(
      name: "EscrowPayments",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EscrowPayments>;
    getContractAt(
      name: "InstaDocHub",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.InstaDocHub>;
    getContractAt(
      name: "PatientRecords",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PatientRecords>;

    deployContract(
      name: "ConsentRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ConsentRegistry>;
    deployContract(
      name: "Counter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Counter>;
    deployContract(
      name: "DoctorRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DoctorRegistry>;
    deployContract(
      name: "EscrowPayments",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EscrowPayments>;
    deployContract(
      name: "InstaDocHub",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.InstaDocHub>;
    deployContract(
      name: "PatientRecords",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PatientRecords>;

    deployContract(
      name: "ConsentRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ConsentRegistry>;
    deployContract(
      name: "Counter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Counter>;
    deployContract(
      name: "DoctorRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DoctorRegistry>;
    deployContract(
      name: "EscrowPayments",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EscrowPayments>;
    deployContract(
      name: "InstaDocHub",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.InstaDocHub>;
    deployContract(
      name: "PatientRecords",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PatientRecords>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
