/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ConsentRegistry } from "./ConsentRegistry";
export type { Counter } from "./Counter";
export type { DoctorRegistry } from "./DoctorRegistry";
export type { EscrowPayments } from "./EscrowPayments";
export type { InstaDocHub } from "./InstaDocHub";
export type { PatientRecords } from "./PatientRecords";
export * as factories from "./factories";
export { ConsentRegistry__factory } from "./factories/ConsentRegistry__factory";
export { Counter__factory } from "./factories/Counter__factory";
export { DoctorRegistry__factory } from "./factories/DoctorRegistry__factory";
export { EscrowPayments__factory } from "./factories/EscrowPayments__factory";
export { InstaDocHub__factory } from "./factories/InstaDocHub__factory";
export { PatientRecords__factory } from "./factories/PatientRecords__factory";
