/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace PatientRecords {
  export type RecordStruct = {
    doctor: AddressLike;
    description: string;
    ipfsHash: string;
    timestamp: BigNumberish;
  };

  export type RecordStructOutput = [
    doctor: string,
    description: string,
    ipfsHash: string,
    timestamp: bigint
  ] & {
    doctor: string;
    description: string;
    ipfsHash: string;
    timestamp: bigint;
  };
}

export interface InstaDocHubInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addRecordForPatient"
      | "consentRegistry"
      | "doctorRegistry"
      | "escrow"
      | "isDoctorVerified"
      | "patientRecords"
      | "registerPatient"
      | "registeredPatients"
      | "viewMyRecords"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PatientRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "addRecordForPatient",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "consentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "doctorRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "escrow", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isDoctorVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "patientRecords",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerPatient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registeredPatients",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "viewMyRecords",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addRecordForPatient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "consentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "doctorRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isDoctorVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "patientRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPatient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredPatients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewMyRecords",
    data: BytesLike
  ): Result;
}

export namespace PatientRegisteredEvent {
  export type InputTuple = [patient: AddressLike];
  export type OutputTuple = [patient: string];
  export interface OutputObject {
    patient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InstaDocHub extends BaseContract {
  connect(runner?: ContractRunner | null): InstaDocHub;
  waitForDeployment(): Promise<this>;

  interface: InstaDocHubInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addRecordForPatient: TypedContractMethod<
    [patient: AddressLike, description: string, recordCID: string],
    [void],
    "nonpayable"
  >;

  consentRegistry: TypedContractMethod<[], [string], "view">;

  doctorRegistry: TypedContractMethod<[], [string], "view">;

  escrow: TypedContractMethod<[], [string], "view">;

  isDoctorVerified: TypedContractMethod<
    [doctor: AddressLike],
    [boolean],
    "view"
  >;

  patientRecords: TypedContractMethod<[], [string], "view">;

  registerPatient: TypedContractMethod<[], [void], "nonpayable">;

  registeredPatients: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  viewMyRecords: TypedContractMethod<
    [],
    [PatientRecords.RecordStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addRecordForPatient"
  ): TypedContractMethod<
    [patient: AddressLike, description: string, recordCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "consentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "doctorRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isDoctorVerified"
  ): TypedContractMethod<[doctor: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "patientRecords"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerPatient"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registeredPatients"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "viewMyRecords"
  ): TypedContractMethod<[], [PatientRecords.RecordStructOutput[]], "view">;

  getEvent(
    key: "PatientRegistered"
  ): TypedContractEvent<
    PatientRegisteredEvent.InputTuple,
    PatientRegisteredEvent.OutputTuple,
    PatientRegisteredEvent.OutputObject
  >;

  filters: {
    "PatientRegistered(address)": TypedContractEvent<
      PatientRegisteredEvent.InputTuple,
      PatientRegisteredEvent.OutputTuple,
      PatientRegisteredEvent.OutputObject
    >;
    PatientRegistered: TypedContractEvent<
      PatientRegisteredEvent.InputTuple,
      PatientRegisteredEvent.OutputTuple,
      PatientRegisteredEvent.OutputObject
    >;
  };
}
