/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace PatientRecords {
  export type RecordStruct = {
    doctor: AddressLike;
    description: string;
    ipfsHash: string;
    timestamp: BigNumberish;
    encrypted: boolean;
  };

  export type RecordStructOutput = [
    doctor: string,
    description: string,
    ipfsHash: string,
    timestamp: bigint,
    encrypted: boolean
  ] & {
    doctor: string;
    description: string;
    ipfsHash: string;
    timestamp: bigint;
    encrypted: boolean;
  };
}

export interface PatientRecordsInterface extends Interface {
  getFunction(nameOrSignature: "addRecord" | "getRecords"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RecordAdded"): EventFragment;

  encodeFunctionData(
    functionFragment: "addRecord",
    values: [AddressLike, AddressLike, string, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecords",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addRecord", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRecords", data: BytesLike): Result;
}

export namespace RecordAddedEvent {
  export type InputTuple = [
    patient: AddressLike,
    doctor: AddressLike,
    description: string,
    ipfsHash: string,
    timestamp: BigNumberish,
    encrypted: boolean
  ];
  export type OutputTuple = [
    patient: string,
    doctor: string,
    description: string,
    ipfsHash: string,
    timestamp: bigint,
    encrypted: boolean
  ];
  export interface OutputObject {
    patient: string;
    doctor: string;
    description: string;
    ipfsHash: string;
    timestamp: bigint;
    encrypted: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PatientRecords extends BaseContract {
  connect(runner?: ContractRunner | null): PatientRecords;
  waitForDeployment(): Promise<this>;

  interface: PatientRecordsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addRecord: TypedContractMethod<
    [
      patient: AddressLike,
      doctor: AddressLike,
      description: string,
      ipfsHash: string,
      encrypted: boolean
    ],
    [void],
    "nonpayable"
  >;

  getRecords: TypedContractMethod<
    [patient: AddressLike],
    [PatientRecords.RecordStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addRecord"
  ): TypedContractMethod<
    [
      patient: AddressLike,
      doctor: AddressLike,
      description: string,
      ipfsHash: string,
      encrypted: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRecords"
  ): TypedContractMethod<
    [patient: AddressLike],
    [PatientRecords.RecordStructOutput[]],
    "view"
  >;

  getEvent(
    key: "RecordAdded"
  ): TypedContractEvent<
    RecordAddedEvent.InputTuple,
    RecordAddedEvent.OutputTuple,
    RecordAddedEvent.OutputObject
  >;

  filters: {
    "RecordAdded(address,address,string,string,uint256,bool)": TypedContractEvent<
      RecordAddedEvent.InputTuple,
      RecordAddedEvent.OutputTuple,
      RecordAddedEvent.OutputObject
    >;
    RecordAdded: TypedContractEvent<
      RecordAddedEvent.InputTuple,
      RecordAddedEvent.OutputTuple,
      RecordAddedEvent.OutputObject
    >;
  };
}
